default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contractor_app_development

test:
  <<: *default
  database: contractor_app_test

production:
  <<: *default
  database: contractor_app_production
  username: contractor_app
  password: <%= ENV['CONTRACTOR_APP_DATABASE_PASSWORD'] %>
